export type CountryCodeOption = {
  id: string;
  country: string;
  code: string;
};

export const countryCodes: CountryCodeOption[] = [
  { id: "AF", country: "Afghanistan", code: "+93" },
  { id: "AL", country: "Albania", code: "+355" },
  { id: "DZ", country: "Algeria", code: "+213" },
  { id: "AD", country: "Andorra", code: "+376" },
  { id: "AO", country: "Angola", code: "+244" },
  { id: "AG", country: "Antigua and Barbuda", code: "+1-268" },
  { id: "AR", country: "Argentina", code: "+54" },
  { id: "AM", country: "Armenia", code: "+374" },
  { id: "AU", country: "Australia", code: "+61" },
  { id: "AT", country: "Austria", code: "+43" },
  { id: "AZ", country: "Azerbaijan", code: "+994" },
  { id: "BS", country: "Bahamas", code: "+1-242" },
  { id: "BH", country: "Bahrain", code: "+973" },
  { id: "BD", country: "Bangladesh", code: "+880" },
  { id: "BB", country: "Barbados", code: "+1-246" },
  { id: "BY", country: "Belarus", code: "+375" },
  { id: "BE", country: "Belgium", code: "+32" },
  { id: "BZ", country: "Belize", code: "+501" },
  { id: "BJ", country: "Benin", code: "+229" },
  { id: "BT", country: "Bhutan", code: "+975" },
  { id: "BO", country: "Bolivia", code: "+591" },
  { id: "BA", country: "Bosnia and Herzegovina", code: "+387" },
  { id: "BW", country: "Botswana", code: "+267" },
  { id: "BR", country: "Brazil", code: "+55" },
  { id: "BN", country: "Brunei", code: "+673" },
  { id: "BG", country: "Bulgaria", code: "+359" },
  { id: "BF", country: "Burkina Faso", code: "+226" },
  { id: "BI", country: "Burundi", code: "+257" },
  { id: "CV", country: "Cabo Verde", code: "+238" },
  { id: "KH", country: "Cambodia", code: "+855" },
  { id: "CM", country: "Cameroon", code: "+237" },
  { id: "CA", country: "Canada", code: "+1" },
  { id: "CF", country: "Central African Republic", code: "+236" },
  { id: "TD", country: "Chad", code: "+235" },
  { id: "CL", country: "Chile", code: "+56" },
  { id: "CN", country: "China", code: "+86" },
  { id: "CO", country: "Colombia", code: "+57" },
  { id: "KM", country: "Comoros", code: "+269" },
  { id: "CG", country: "Congo", code: "+242" },
  { id: "CR", country: "Costa Rica", code: "+506" },
  { id: "CI", country: "Cote d'Ivoire", code: "+225" },
  { id: "HR", country: "Croatia", code: "+385" },
  { id: "CU", country: "Cuba", code: "+53" },
  { id: "CY", country: "Cyprus", code: "+357" },
  { id: "CZ", country: "Czechia", code: "+420" },
  { id: "CD", country: "Democratic Republic of the Congo", code: "+243" },
  { id: "DK", country: "Denmark", code: "+45" },
  { id: "DJ", country: "Djibouti", code: "+253" },
  { id: "DM", country: "Dominica", code: "+1-767" },
  { id: "DO", country: "Dominican Republic", code: "+1-809" },
  { id: "EC", country: "Ecuador", code: "+593" },
  { id: "EG", country: "Egypt", code: "+20" },
  { id: "SV", country: "El Salvador", code: "+503" },
  { id: "GQ", country: "Equatorial Guinea", code: "+240" },
  { id: "ER", country: "Eritrea", code: "+291" },
  { id: "EE", country: "Estonia", code: "+372" },
  { id: "SZ", country: "Eswatini", code: "+268" },
  { id: "ET", country: "Ethiopia", code: "+251" },
  { id: "FJ", country: "Fiji", code: "+679" },
  { id: "FI", country: "Finland", code: "+358" },
  { id: "FR", country: "France", code: "+33" },
  { id: "GA", country: "Gabon", code: "+241" },
  { id: "GM", country: "Gambia", code: "+220" },
  { id: "GE", country: "Georgia", code: "+995" },
  { id: "DE", country: "Germany", code: "+49" },
  { id: "GH", country: "Ghana", code: "+233" },
  { id: "GR", country: "Greece", code: "+30" },
  { id: "GD", country: "Grenada", code: "+1-473" },
  { id: "GT", country: "Guatemala", code: "+502" },
  { id: "GN", country: "Guinea", code: "+224" },
  { id: "GW", country: "Guinea-Bissau", code: "+245" },
  { id: "GY", country: "Guyana", code: "+592" },
  { id: "HT", country: "Haiti", code: "+509" },
  { id: "VA", country: "Holy See", code: "+379" },
  { id: "HN", country: "Honduras", code: "+504" },
  { id: "HU", country: "Hungary", code: "+36" },
  { id: "IS", country: "Iceland", code: "+354" },
  { id: "IN", country: "India", code: "+91" },
  { id: "ID", country: "Indonesia", code: "+62" },
  { id: "IR", country: "Iran", code: "+98" },
  { id: "IQ", country: "Iraq", code: "+964" },
  { id: "IE", country: "Ireland", code: "+353" },
  { id: "IL", country: "Israel", code: "+972" },
  { id: "IT", country: "Italy", code: "+39" },
  { id: "JM", country: "Jamaica", code: "+1-876" },
  { id: "JP", country: "Japan", code: "+81" },
  { id: "JO", country: "Jordan", code: "+962" },
  { id: "KZ", country: "Kazakhstan", code: "+7" },
  { id: "KE", country: "Kenya", code: "+254" },
  { id: "KI", country: "Kiribati", code: "+686" },
  { id: "KW", country: "Kuwait", code: "+965" },
  { id: "KG", country: "Kyrgyzstan", code: "+996" },
  { id: "LA", country: "Laos", code: "+856" },
  { id: "LV", country: "Latvia", code: "+371" },
  { id: "LB", country: "Lebanon", code: "+961" },
  { id: "LS", country: "Lesotho", code: "+266" },
  { id: "LR", country: "Liberia", code: "+231" },
  { id: "LY", country: "Libya", code: "+218" },
  { id: "LI", country: "Liechtenstein", code: "+423" },
  { id: "LT", country: "Lithuania", code: "+370" },
  { id: "LU", country: "Luxembourg", code: "+352" },
  { id: "MG", country: "Madagascar", code: "+261" },
  { id: "MW", country: "Malawi", code: "+265" },
  { id: "MY", country: "Malaysia", code: "+60" },
  { id: "MV", country: "Maldives", code: "+960" },
  { id: "ML", country: "Mali", code: "+223" },
  { id: "MT", country: "Malta", code: "+356" },
  { id: "MH", country: "Marshall Islands", code: "+692" },
  { id: "MR", country: "Mauritania", code: "+222" },
  { id: "MU", country: "Mauritius", code: "+230" },
  { id: "MX", country: "Mexico", code: "+52" },
  { id: "FM", country: "Micronesia", code: "+691" },
  { id: "MD", country: "Moldova", code: "+373" },
  { id: "MC", country: "Monaco", code: "+377" },
  { id: "MN", country: "Mongolia", code: "+976" },
  { id: "ME", country: "Montenegro", code: "+382" },
  { id: "MA", country: "Morocco", code: "+212" },
  { id: "MZ", country: "Mozambique", code: "+258" },
  { id: "MM", country: "Myanmar", code: "+95" },
  { id: "NA", country: "Namibia", code: "+264" },
  { id: "NR", country: "Nauru", code: "+674" },
  { id: "NP", country: "Nepal", code: "+977" },
  { id: "NL", country: "Netherlands", code: "+31" },
  { id: "NZ", country: "New Zealand", code: "+64" },
  { id: "NI", country: "Nicaragua", code: "+505" },
  { id: "NE", country: "Niger", code: "+227" },
  { id: "NG", country: "Nigeria", code: "+234" },
  { id: "KP", country: "North Korea", code: "+850" },
  { id: "MK", country: "North Macedonia", code: "+389" },
  { id: "NO", country: "Norway", code: "+47" },
  { id: "OM", country: "Oman", code: "+968" },
  { id: "PK", country: "Pakistan", code: "+92" },
  { id: "PW", country: "Palau", code: "+680" },
  { id: "PS", country: "Palestine", code: "+970" },
  { id: "PA", country: "Panama", code: "+507" },
  { id: "PG", country: "Papua New Guinea", code: "+675" },
  { id: "PY", country: "Paraguay", code: "+595" },
  { id: "PE", country: "Peru", code: "+51" },
  { id: "PH", country: "Philippines", code: "+63" },
  { id: "PL", country: "Poland", code: "+48" },
  { id: "PT", country: "Portugal", code: "+351" },
  { id: "QA", country: "Qatar", code: "+974" },
  { id: "RO", country: "Romania", code: "+40" },
  { id: "RU", country: "Russia", code: "+7" },
  { id: "RW", country: "Rwanda", code: "+250" },
  { id: "KN", country: "Saint Kitts and Nevis", code: "+1-869" },
  { id: "LC", country: "Saint Lucia", code: "+1-758" },
  { id: "VC", country: "Saint Vincent and the Grenadines", code: "+1-784" },
  { id: "WS", country: "Samoa", code: "+685" },
  { id: "SM", country: "San Marino", code: "+378" },
  { id: "ST", country: "Sao Tome and Principe", code: "+239" },
  { id: "SA", country: "Saudi Arabia", code: "+966" },
  { id: "SN", country: "Senegal", code: "+221" },
  { id: "RS", country: "Serbia", code: "+381" },
  { id: "SC", country: "Seychelles", code: "+248" },
  { id: "SL", country: "Sierra Leone", code: "+232" },
  { id: "SG", country: "Singapore", code: "+65" },
  { id: "SK", country: "Slovakia", code: "+421" },
  { id: "SI", country: "Slovenia", code: "+386" },
  { id: "SB", country: "Solomon Islands", code: "+677" },
  { id: "SO", country: "Somalia", code: "+252" },
  { id: "ZA", country: "South Africa", code: "+27" },
  { id: "KR", country: "South Korea", code: "+82" },
  { id: "SS", country: "South Sudan", code: "+211" },
  { id: "ES", country: "Spain", code: "+34" },
  { id: "LK", country: "Sri Lanka", code: "+94" },
  { id: "SD", country: "Sudan", code: "+249" },
  { id: "SR", country: "Suriname", code: "+597" },
  { id: "SE", country: "Sweden", code: "+46" },
  { id: "CH", country: "Switzerland", code: "+41" },
  { id: "SY", country: "Syria", code: "+963" },
  { id: "TJ", country: "Tajikistan", code: "+992" },
  { id: "TZ", country: "Tanzania", code: "+255" },
  { id: "TH", country: "Thailand", code: "+66" },
  { id: "TL", country: "Timor-Leste", code: "+670" },
  { id: "TG", country: "Togo", code: "+228" },
  { id: "TO", country: "Tonga", code: "+676" },
  { id: "TT", country: "Trinidad and Tobago", code: "+1-868" },
  { id: "TN", country: "Tunisia", code: "+216" },
  { id: "TR", country: "Turkey", code: "+90" },
  { id: "TM", country: "Turkmenistan", code: "+993" },
  { id: "TV", country: "Tuvalu", code: "+688" },
  { id: "UG", country: "Uganda", code: "+256" },
  { id: "UA", country: "Ukraine", code: "+380" },
  { id: "AE", country: "United Arab Emirates", code: "+971" },
  { id: "GB", country: "United Kingdom", code: "+44" },
  { id: "US", country: "United States", code: "+1" },
  { id: "UY", country: "Uruguay", code: "+598" },
  { id: "UZ", country: "Uzbekistan", code: "+998" },
  { id: "VU", country: "Vanuatu", code: "+678" },
  { id: "VE", country: "Venezuela", code: "+58" },
  { id: "VN", country: "Vietnam", code: "+84" },
  { id: "YE", country: "Yemen", code: "+967" },
  { id: "ZM", country: "Zambia", code: "+260" },
  { id: "ZW", country: "Zimbabwe", code: "+263" },
];

export function getFlagUrl(countryId: string) {
  return `https://flagcdn.com/w40/${countryId.toLowerCase()}.png`;
}
